name: Bug Report
description: Create a report to help us reproduce and fix the bug.
labels: bug
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: |
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Run '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: exa-cli Version
      description: The version of exa-cli you are using (e.g., 1.0.0)
      placeholder: npm list exa-cli

  - type: input
    id: node-version
    attributes:
      label: Node Version
      description: The Node.js version (e.g., v20.10.0)
      placeholder: node --version

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: The operating system where the bug occurred
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please include any relevant log output or error messages.
      render: shell
