name: Feature Request
description: Suggest an idea for this project.
labels: enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: |
        Describe the problem you are trying to solve.
        Why is this needed? What pain point does it address?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: |
        Describe the solution you'd like to see implemented.
        How should it work? What API/design do you propose?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: |
        Describe any alternative solutions or workarounds you've considered.
        What are the tradeoffs?

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: |
        Add any other context about the feature request here.
        Include links to related issues, mockups, or examples.
